services:
  - type: web
    name: smmnotcoin-frontend
    env: static
    buildCommand: yarn --frozen-lockfile install; yarn build
    staticPublishPath: ./dist
    routes:
      # Redirect rules
      - type: rewrite
        source: "/*"
        destination: /index.html
